#!/usr/bin/env bash
# Function to display information about a subdomain
display_info() {
    local sub_domain=$1
    local record_type=$(dig +short $sub_domain | awk '{ print $4 }')
    local destination=$(dig +short $sub_domain)

    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Check if the script is provided with the correct number of arguments
if [ "$#" -eq 1 ]; then
    # Display information for default subdomains
    display_info "www.$1"
    display_info "lb-01.$1"
    display_info "web-01.$1"
    display_info "web-02.$1"
elif [ "$#" -eq 2 ]; then
    # Display information for the specified subdomain
    display_info "$2.$1"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

