#!/usr/bin/env bash
# Install nginx on web server; 
# Nginx should be listening on port 80

# This method 
#sudo apt-get -y update
#sudo apt-get -y install nginx
#sudo ufw allow "Nginx HTTP"
#sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
#sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
#sudo service nginx restart

#OR THis
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html;
}
" > /etc/nginx/sites-available/default

service nginx restart
