#!/usr/bin/env bash
# Install nginx on web server; 
# Nginx should be listening on port 80

# This method 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

#OR THis
# apt-get -y update
#apt-get -y install nginx

#touch /var/www/html/index.html
#echo "Hello World!" > /var/www/html/index.html

#printf %s "server {
#    listen              80 default_server;
#    listen              [::]:80 default_server;

#    root                /var/www/html;
#    index               index.html index.htm index.nginx-debian.html;
#}
#" > /etc/nginx/sites-available/default

#service nginx restart
