#!/usr/bin/env bash
# Bash script that displays list of current running proceses
# Requirements:

# Must show all processes, for all users,
# including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy
ps -auxf
