#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process.
# Requirements:

# You cannot use kill or killall
# pkill -15 "bash.<file_name>" -f
# OR
pkill -f "4-to_infinity_and_beyond"
