#!/usr/bin/env bash
# This bash script display "Best school" 10 times
# but print Hi at line 9
a=0
while [ $a -lt 10 ]
do
    echo "Best School"
    ((a++))
    if [ $a -eq 9 ]; then
        echo "Hi"
    fi
done
