#!/usr/bin/env bash
# This bash script loops from 1 to 10 and displays bad luck on # the 4th loop iteration also displays good luck the 8th loop
# iteration

a=1
while [ "$a" -le 10 ]
do
    if [ $a -eq 4 ]; then
        echo "bad luck"
    elif [ $a -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((a++))
done
