#!/usr/bin/env bash
# This bash script displays numbers from 1 to 20 and also
# displays 4 and then bad luck from China on the 4th loop iteration 
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

a=1
while [ $a -le 20 ]
do
    echo $a
    case $a in
        4)
		echo "bad luck from China";;
        9)
                echo "bad luck from Japan"
                ;;
        17)
            echo "bad luck from Italy"
            ;;
   esac
   ((a++))
done
