#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.


# Use the 'ip' command instead of 'ifconfig' to retrieve IPv4 addresses
ip -4 addr show | grep -Eo "inet ([0-9]*\.){3}[0-9]*" | cut -d' ' -f2


# ifconfig | grep -Eo "inet (add:)?([0-9]*\.){3}[0-9]*" | cut -b 11-

# ifconfig -a | grep "inet addr" | cut -d " " -f12 | cut -d ":" -f2

# Another way to use it
# ifconfig | awk -F "[: ]+" '/inet addr:/ { print $4 }'
